env_name: 'ALE/Alien-v5'
max_train_episode_steps: 2000
max_eval_episode_steps: None
model: 'DQN'
num_training_steps: 2.0e+8
num_envs: 16
batch_size: 32
learning_rate: 0.00025
gamma: 0.99
target_update_freq: 10000
memory_size: 200000
epsilon_start: 1.0
epsilon_end: 0.1
epsilon_decay: 1.0e-6  # Ensure this is interpreted as a float
frame_skip: 4
eval_interval: 20000
num_eval_episodes: 10
eps_eval: 0.00
input_mode: 'grey'  # Use 'rgb' to process RGB frames, 'grayscale' to process grayscale frames